### PR TITLE
This module is now a hybrid ESM/CommonJS package that works under node or webpack

### PR DESCRIPTION
**Pull request by ehoogerbeets**

### CODE REVIEW

**Comment by ehoogerbeets** [comment]
This one is next

**Comment by gouniLee** [comment]
test with cricleCI didn't work. Do you think would it be okay to ignore this situation?
i.e) https://app.circleci.com/pipelines/github/iLib-js/ilib-common/36/workflows/cd5015d5-3980-4186-bfd2-23451c7074b9/jobs/180

**Comment by ehoogerbeets** [comment]
Now it passed. A circleci support person fixed up the project.

**Comment by gouniLee** [comment]
> Now it passed. A circleci support person fixed up the project.
oh. That's good. I hope other repository work too.

**Review by gouniLee — APPROVED** [review]

**Pull request merged**
